services:

  oracle:

    # Docker Hub image (feel free to change the tag "latest" to any other available one)
    image: gvenzl/oracle-xe:21-full

    container_name: oracle-db

    # Provide passwords and other environment variables to container
    environment:
      ORACLE_PASSWORD: welcome1

    # Forward Oracle port
    ports:
      - 1522:1521

    # Mount a volume with SQL script to create a user and grant DBA privileges
    volumes:
      - ./create_user_and_grant_privileges.sql:/docker-entrypoint-initdb.d/create_user_and_grant_privileges.sql